### PR TITLE
Meets10_376_files_Guzel

### PR DESCRIPTION
**Pull request by Guzelzlv**
I finished my "US-006 Folder View Functionality", you can review it

### CODE REVIEW

**Review by Tosungulsah — COMMENTED** [review]
All look good, thank you guzel.

**Comment by Tosungulsah** [comment]
Reviewed thank you, all look good.

**Comment by Guzelzlv** [comment]
please just do review, without closing

**Comment by Tosungulsah** [comment]
All look good, thank you guzel.


Reviewing without closing. Thanks

**Review by Tosungulsah — COMMENTED** [review]
I reviewed all codes again

**Review by Tosungulsah — APPROVED** [review]
This is for approving

**Pull request merged**
